module.exports =  {    
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",
    AUTH_EOROR: "AUTH_ERROR",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    EMAIL_CHECKOUT_SUCCESS: "EMAIL_CHECKOUT_SUCCESS",
    PASSWORD_RESET_FAIL : "PASSWORD_RESET_FAIL",
    REGISTER_FAIL: "REGISTER_FAIL",
    GET_ERROR: "GET_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    EMAIL_CHECKOUT_FAIL: "EMAIL_CHECKOUT_FAIL"
};
